baseURL = "https://hjemmekino.no/"
languageCode = "nb-NO"
defaultContentLanguage = "nb"
title = "Hjemmekino.no"
theme = "referanserommet"
enableRobotsTXT = true
enableGitInfo = false
summaryLength = 28

[params]
  description = "Uavhengig norsk kunnskapsplattform for hjemmekino, HiFi og AV-teknologi."
  tagline = "Film er best hjemme"
  since = "1998"

[taxonomies]
  tag = "tags"
  category = "categories"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false

[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML"]

[outputFormats.JSON]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = true

[security]
  enableInlineShortcodes = false
